---
- name: Install Mysql and dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - python-mysqldb
    - mysql-server
    - php5-mysql

- name: Copy my.cnf template
  template:
    src: "my.cnf.tpl"
    dest: "/etc/mysql/my.cnf"
    owner: root
    group: root
  notify: restart mysql

- name: Start Mysql
  service: name=mysql enabled=yes state=started

 # 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ db_pass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes
  notify: restart mysql

- name: copy .my.cnf file with root password credentials
  template: src=root/my.conf dest=/root/.my.cnf owner=root mode=0600