---

- { include: apt.yml }
- { include: users.yml }
- { include: mosh.yml}
- { include: hostname.yml, when: hostname is defined }

- name: Install default locale
  locale_gen: name={{ default_locale }} state=present

# https://www.thomas-krenn.com/de/wiki/Locales_unter_Ubuntu_konfigurieren
# https://github.com/ansible/ansible/issues/7246
- name: Set default locale
  template:
    src: locale
    dest: "/etc/default/locale"
    owner: root
    group: root
    mode: "0644"

- name: Set timezone variables
  copy:
    content: "{{ timezone }}"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: "0644"
  notify:
    - update timezone

